markers: # MATERIAL : 0-26
  WHITE_DYE: 7
  BONE_MEAL: 6
  CYAN_DYE: 9
  BROWN_DYE: 8
  RED_DYE: 5 # Если к красной стрелочке вниз добавить красный/белый (4) краситель, получится соответствующий крестик, а карта станет непрогруженной

rename: true # Если карта изначально имеет имя, то её имя нанесётся на неё поверх

font:
  offset:
    x: 0 # Отступ по X
    y: 0 # Отступ по Z

color_map: true # Цвет флага = цвет текста на карте