name: FelmonMapMarkers
version: '${project.version}'
main: net.aniby.felmonmapmarkers.FelmonMapMarkers
api-version: '1.20'
load: STARTUP
authors: [An1by]
description: Plugin for marker setting on a map
website: https://aniby.net/
